;; load all test code ./test
(gbc)
(load "./test/object-test.lsp")
(load "./test/arithmetic-test.lsp")
(load "./test/array-test.lsp")
(load "./test/controle-test.lsp")
(load "./test/convert-test.lsp")
(load "./test/list-test.lsp")
(load "./test/predicate-test.lsp")
(load "./test/symbol-test.lsp")
