(import "test")
(import "matrix")

(let ((test-vector #(1 2 3))
      (identity-matrix 
        #2a((1 0 0)
            (0 1 0)
            (0 0 1)))
      (zeros-matrix
        #2a((0 0 0)
            (0 0 0)
            (0 0 0)))
      (test-matrix 
        #2a((1 2 3)
            (4 5 6)
            (7 8 9))))
  ($ap 2 "rows")
  ($test-assert (matrix::rows identity-matrix)
         #(#(1 0 0) #(0 1 0) #(0 0 1)))
  ($test-assert (matrix::rows test-matrix)
         #(#(1 2 3) #(4 5 6) #(7 8 9)))
  ($ap 2 "columns")
  ($test-assert (matrix::columns test-matrix)
         #(#(1 4 7) #(2 5 8) #(3 6 9)))
  ($ap 2 "rows->matrix")
  ($test-assert (matrix::rows->matrix (matrix::rows test-matrix)) test-matrix)
  ($ap 2 "transpose")
  ($ap 3 "transpose matrix")
  ($test-assert (matrix::transpose (matrix::transpose test-matrix)) test-matrix)
  ($ap 3 "transpose vector")
  ($test-assert (matrix::transpose (matrix::transpose test-vector)) test-vector)
  ($ap 2 "columns->matrix")
  ($test-assert (matrix::columns->matrix (matrix::columns test-matrix)) test-matrix)

  ($ap 2 "add")
  ($ap 3 "add scalar")
  ($test-assert (matrix::add 1 2) 3)
  ($ap 3 "add vector")
  ($test-assert (matrix::add #(1 2 3) #(4 5 6)) #(5 7 9))
  ($ap 3 "add matrix")
  ($test-assert (matrix::add identity-matrix identity-matrix) 
         #2a((2 0 0)
             (0 2 0)
             (0 0 2)))
  
  ($ap 2 "sub")
  ($ap 2 "sub scalar")
  ($test-assert (matrix::sub 2 1) 1)
  ($ap 2 "sub vector")
  ($test-assert (matrix::sub #(4 5 6) #(1 2 3)) #(3 3 3))
  ($ap 2 "sub matrix")
  ($test-assert (matrix::sub test-matrix identity-matrix)
         #2a((0 2 3)
             (4 4 6)
             (7 8 8)))
  ($test-assert (matrix::sub test-matrix test-matrix) zeros-matrix)

  ($ap 2 "dot")
  ($test-assert (matrix::dot #(1 2 3) #(1 1 1)) 6)
  ($test-assert (matrix::dot #(1 2 3) #(0 0 0)) 0)

  ($ap 2 "mult")
  ($ap 3 "mult scalar scalar")
  ($test-assert (matrix::mult 2 3) 6)
  ($ap 3 "mult vector scalar")
  ($test-assert (matrix::mult #(1 2 3) 2) #(2 4 6))
  ($ap 3 "mult vector matrix")
  ($test-assert (matrix::mult test-vector identity-matrix) test-vector)
  ($ap 3 "mult matrix matrix")
  ($test-assert (matrix::mult test-matrix identity-matrix) test-matrix)
  

  )
