#!/bin/sh
#
# nana-trace.in - does a line by line trace of a program
#
# Copyright (c) 1995,1996,1997 Phil Maker
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

case $1 
in
    --version)
	  echo "nana-trace (nana) 3.0"
	  echo "Copyright (C) 1997 Phil Maker"
	  echo "Nana comes with NO WARRANTY, to the extent permitted by law."
	  echo "You may redistribute copies of nana without charge."
	  echo "See the file COPYING for more details."
	  exit 0 
          ;;
    --help)
	  echo "usage: nana-trace [gdb arguments ...]"
	  echo ""
	  echo "Does a line by line trace of your program using gdb."
	  echo "  Note that breakpoint messages etc are filtered out"
	  echo "  by this program"
	  echo ""
	  echo "See also:"
	  echo "  <ftp://ftp.cs.ntu.edu.au/pub/nana>"
	  echo "  <http://www.cs.ntu.edu.au/homepages/pjm/nana-home>"
	  echo ""
	  echo "Report suggestions to majordomo list - nana@it.ntu.edu.au"  
	  echo "Report bugs to nana-bug@it.ntu.edu.au"
	  exit 0 
	  ;;
esac


prefix=/usr/local
exec_prefix=${prefix}

gdb -batch $* -x ${exec_prefix}/libexec/nana-trace.gdb 2>&1 | 
gawk '
BEGIN {
	printing = 0
}

{
	if($0 ~ /^Breakpoint 1, main()/) { 
		printing = 1 
	} else if($0 ~ /^Program exited with code/) { 
		printing = 0 
	} else if(printing) {
		print $0 
	} # else ignore it
}
'

