;; 
(load "verify/array.lsp")
(load "verify/char.lsp")
(load "verify/cond.lsp")
(load "verify/declare.lsp")
(load "verify/string.lsp")
;(load "verify/formeval.lsp")
(load "verify/files.lsp")
(load "verify/io.lsp")
(load "verify/list.lsp")
(load "verify/macro.lsp")
;(load "verify/misc.lsp")
(load "verify/number.lsp")
(load "verify/object.lsp")
(load "verify/pred.lsp")
(load "verify/seq.lsp")
(load "verify/stream.lsp")
(load "verify/symbol.lsp")
(load "verify/vector.lsp")

