#!/bin/sh
#
# nana-sfdir.sh - run's nana-sfg over a set of C, C++ source files in 
#    the current directory
# 
# Copyright (c) 1998 Phil Maker <pjm@gnu.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $Id: nana-sfdir.in,v 1.1.1.1 1999/09/12 03:26:49 pjm Exp $
#

prefix=/usr/local
exec_prefix=${prefix}

# TARGET = directory to put the generated source in
#   (typically the HTML will be in $TARGET/HTML/index.html for the
#    GLOBAL package)
TARGET=NANASF

# clean $TARGET
rm -rf $TARGET

# make the target directory
mkdir $TARGET

# Note: SUN's find doesn't have a -or use -o

# copy the directory tree from . into $TARGET excluding $TARGET
find . \( -name $TARGET -prune \) -o \
       \( -type d ! -name . \) -exec mkdir $TARGET/{} \;

# generate shortform'ed code from . to $TARGET excluding $TARGET
find . \( -name $TARGET -prune \) -o \
       \( -name \*.c -o \
          -name \*.C -o \
          -name \*.cc -o \
	  -name \*.cxx -o \
	  -name \*.m -o \
	  -name \*.h \) -print |
while read f
do
    ${exec_prefix}/${exec_prefix}/bin/nana-sfg $f >$TARGET/$f
done













